apiVersion: v1
kind: Service
metadata:
  name: pulse-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pulse-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
