[package]
name = "pulse_consent"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
